# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.7

# what branches should be evaluated
branches:
    only:
        - main


before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      # Install from latest CRAN binary build for OS X
      wget https://cloud.r-project.org/bin/macosx/R-latest.pkg -O /tmp/R-latest.pkg
      echo "Installing OS X binary package for R"
      sudo installer -pkg "/tmp/R-latest.pkg" -target /
      rm "/tmp/R-latest.pkg"
      brew upgrade python3
      python3 -m venv py3_env
      source py3_env/bin/activate
    else
      sudo apt-key adv \
        --keyserver keyserver.ubuntu.com \
        --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
      sudo add-apt-repository \
        --yes \
        "deb https://cloud.r-project.org/bin/linux/ubuntu/ $(lsb_release -c -s)-cran35/"
      cat /etc/apt/sources.list
      sudo apt-get update -qq
      sudo apt-get install -y r-base
      if [[ $RPY2_CFFI_MODE == 'API' ]]; then
        sudo apt-get install -y r-base-dev
      fi
    fi

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install -r requirements.txt

# the actual commands to run
script:
    - coverage run test/test_avo.py
    - coverage run test/test_linear_model.py
    - coverage run test/test_t_test.py

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls